"""Render docs/03-analysis-insights(.vi).md from analysis_bundle(): commentary, then tables."""

from pathlib import Path

import duckdb
import polars as pl

from logops.analysis.bundle import analysis_bundle
from logops.analysis.insights import REASONS_VI, SOURCES, THRESHOLDS
from logops.analysis.profit import BRIDGE_PARTS
from logops.data_platform.dq_report import NumberFormatter

LANGUAGES = ("en", "vi")

L = {
    "en": {
        "file": "03-analysis-insights.md",
        "title": "# 03 · Analysis & Insights",
        "banner": "> CRISP-DM phases 2–3 (descriptive and diagnostic). Generated by `uv run logops "
        "build` from `src/logops/analysis/`; do not edit by hand. · Vietnamese: "
        "[03-analysis-insights.vi.md](03-analysis-insights.vi.md) · Spec: "
        "[SPEC-analysis.md](../SPEC-analysis.md)",
        "range": "Period: {start} to {end}. Profit is contribution before driver pay and overhead "
        "(not in the data). Costs are booked on the date they occur.",
        "insights": "## 1. Commentary (generated from the figures by rules)",
        "level": "Level",
        "comment": "Comment",
        "pnl": "## 2. P&L by year",
        "pnl_q": "## 3. P&L by quarter",
        "pnl_cols": [
            "Period",
            "Trips",
            "Revenue",
            "Fuel",
            "Maintenance",
            "Claims",
            "Contribution",
            "Margin",
            "vs previous",
            "vs last year",
        ],
        "pnl_q_cols": [
            "Quarter",
            "Revenue",
            "Contribution",
            "Margin",
            "vs previous",
            "vs last year",
            "YTD",
            "YTD last year",
        ],
        "bridge": "## 4. Profit bridge {a} → {b}",
        "bridge_rows": {
            "start": "Contribution {a}",
            "volume": "Volume",
            "rate": "Rate per trip",
            "fuel_price": "Fuel price",
            "fuel_consumption": "Fuel used per trip",
            "maintenance": "Maintenance",
            "claims": "Claims",
            "end": "Contribution {b}",
        },
        "units": "## 5. Unit economics",
        "unit_cols": [
            "Year",
            "Revenue/mile",
            "Cost/mile",
            "Contribution/mile",
            "Revenue/trip",
            "Contribution/trip",
            "Contribution/truck-week",
        ],
        "dims": "## 6. By business dimension",
        "dim_titles": {
            "customer_type": "Customer segment",
            "load_type": "Load type",
            "origin_state": "Origin state (top 8 by contribution)",
        },
        "dim_cols": ["Group", "Revenue", "Contribution", "Margin", "Share of contribution"],
        "conc": "**Customer concentration:** largest customer {largest}, top 10 {top10}, top 20 "
        "{top20}; {n80} of {n} customers make 80% of revenue; HHI {hhi}.",
        "fuel": "## 7. Fuel (statistics)",
        "fuel_cols": [
            "Year",
            "Gallons bought",
            "Spend",
            "Average price",
            "Gallons burned on trips",
            "Bought ÷ burned",
        ],
        "fuel_corr": "Correlation between monthly margin and monthly fuel price: {corr}.",
        "cap": "## 8. Fleet capacity",
        "cap_cols": ["Year", "Average trucks busy per day", "95th percentile", "Busiest day"],
        "cap_note": "Over the whole period: 95% of days ≤ {p95} trucks, 99% ≤ {p99}, busiest day "
        "{mx}. {in_use} trucks in use, {owned} owned. Day-to-day correlation {lag1}; quarter "
        "pattern across years {qp}.",
        "matrix": "## 9. Lane matrix (3×3, number of lanes)",
        "matrix_head": ["Volume ↓ / Margin →", "Low", "Mid", "High"],
        "tiers": {1: "Low", 2: "Mid", 3: "High"},
        "actions": {
            "protect": "protect",
            "maintain": "maintain",
            "reprice": "reprice",
            "grow": "grow",
            "review_price": "review price",
            "growth_opportunity": "growth opportunity",
            "monitor": "monitor",
            "consider_exit": "consider exit",
        },
        "balance": "## 10. Headhaul / backhaul balance (most imbalanced cities)",
        "bal_cols": ["City", "Loads out", "Loads in", "Net", "Imbalance"],
        "moves": "## 11. Trucks starting where the last trip didn't end",
        "move_cols": ["Year", "Transitions", "Started elsewhere", "Share"],
        "notebook": "## 12. Comparison with the dataset author's notebook",
        "nb_cols": ["Analysis", "Notebook", "Issue", "Here"],
        "nb_rows": [
            (
                "Lane matrix",
                "Fuel at a fixed $3.80/gallon; revenue without surcharges; average of "
                "per-load margins",
                "Assumed price; incomplete revenue; mean of ratios",
                "Real fuel spend, full revenue, sum ÷ sum; average price {price}",
            ),
            (
                "Headhaul/backhaul",
                "Repositioning cost = |sum of net loads| × 400 miles × $0.85",
                "The sum of net loads over all cities is always 0, so the cost is always $0; the "
                "miles and rate are assumed",
                "Inbound surplus measured per city: {surplus} loads",
            ),
            (
                "Customer concentration",
                "Top-10/20 share, 10% risk threshold",
                "None",
                "Same, plus HHI {hhi}",
            ),
            (
                "Seasonality",
                "Monthly load counts, peak vs trough",
                "Months have 28–31 days, so long months always look busier",
                "Counted per day: no recurring pattern",
            ),
            (
                "Empty miles",
                "Assumes 15% empty miles at $0.85/mile",
                "Both numbers are assumed",
                "Counted from trip sequences: {moved} of transitions; no miles (4 lane cities have "
                "no coordinates)",
            ),
        ],
        "thresholds": "## 13. Rule thresholds",
        "th_cols": ["Threshold", "Value", "Reason", "Source"],
    },
    "vi": {
        "file": "03-analysis-insights.vi.md",
        "title": "# 03 · Phân tích và nhận xét",
        "banner": "> CRISP-DM pha 2–3 (mô tả và chẩn đoán). Sinh tự động bằng `uv run logops "
        "build` từ `src/logops/analysis/`; không sửa tay. · Bản tiếng Anh: "
        "[03-analysis-insights.md](03-analysis-insights.md) · Spec: "
        "[SPEC-analysis.vi.md](../SPEC-analysis.vi.md)",
        "range": "Giai đoạn: {start} đến {end}. Lợi nhuận là đóng góp trước lương tài xế và "
        "chi phí chung (không có trong dữ liệu). Chi phí ghi theo ngày phát sinh.",
        "insights": "## 1. Nhận xét (sinh tự động từ số liệu theo quy tắc)",
        "level": "Mức độ",
        "comment": "Nhận xét",
        "pnl": "## 2. Lãi lỗ theo năm",
        "pnl_q": "## 3. Lãi lỗ theo quý",
        "pnl_cols": [
            "Kỳ",
            "Số chuyến",
            "Doanh thu",
            "Nhiên liệu",
            "Bảo dưỡng",
            "Bồi thường",
            "Đóng góp",
            "Biên",
            "So kỳ trước",
            "So cùng kỳ",
        ],
        "pnl_q_cols": [
            "Quý",
            "Doanh thu",
            "Đóng góp",
            "Biên",
            "So kỳ trước",
            "So cùng kỳ",
            "Lũy kế năm",
            "Lũy kế năm trước",
        ],
        "bridge": "## 4. Cầu lợi nhuận {a} → {b}",
        "bridge_rows": {
            "start": "Đóng góp {a}",
            "volume": "Sản lượng",
            "rate": "Giá mỗi chuyến",
            "fuel_price": "Giá nhiên liệu",
            "fuel_consumption": "Nhiên liệu mỗi chuyến",
            "maintenance": "Bảo dưỡng",
            "claims": "Bồi thường",
            "end": "Đóng góp {b}",
        },
        "units": "## 5. Đơn vị kinh tế",
        "unit_cols": [
            "Năm",
            "Doanh thu/dặm",
            "Chi phí/dặm",
            "Đóng góp/dặm",
            "Doanh thu/chuyến",
            "Đóng góp/chuyến",
            "Đóng góp/xe-tuần",
        ],
        "dims": "## 6. Theo chiều kinh doanh",
        "dim_titles": {
            "customer_type": "Phân khúc khách hàng",
            "load_type": "Loại hàng",
            "origin_state": "Bang đi (8 bang đóng góp nhiều nhất)",
        },
        "dim_cols": ["Nhóm", "Doanh thu", "Đóng góp", "Biên", "Tỷ trọng đóng góp"],
        "conc": "**Tập trung khách hàng:** khách lớn nhất {largest}, 10 khách lớn nhất {top10}, 20 "
        "khách lớn nhất {top20}; {n80} trên {n} khách chiếm 80% doanh thu; HHI {hhi}.",
        "fuel": "## 7. Nhiên liệu (thống kê)",
        "fuel_cols": [
            "Năm",
            "Gallon mua",
            "Chi tiêu",
            "Giá trung bình",
            "Gallon tiêu thụ trên chuyến",
            "Mua ÷ tiêu thụ",
        ],
        "fuel_corr": "Tương quan giữa biên hằng tháng và giá nhiên liệu hằng tháng: {corr}.",
        "cap": "## 8. Năng lực đội xe",
        "cap_cols": ["Năm", "Xe bận trung bình mỗi ngày", "Phân vị 95", "Ngày bận nhất"],
        "cap_note": "Cả giai đoạn: 95% số ngày ≤ {p95} xe, 99% ≤ {p99} xe, ngày bận nhất {mx} xe. "
        "{in_use} xe đang chạy, {owned} xe sở hữu. Tương quan giữa hai ngày liền nhau {lag1}; "
        "mẫu hình theo quý qua các năm {qp}.",
        "matrix": "## 9. Ma trận tuyến (3×3, số tuyến)",
        "matrix_head": ["Sản lượng ↓ / Biên →", "Thấp", "Vừa", "Cao"],
        "tiers": {1: "Thấp", 2: "Vừa", 3: "Cao"},
        "actions": {
            "protect": "bảo vệ",
            "maintain": "duy trì",
            "reprice": "điều chỉnh giá",
            "grow": "mở rộng",
            "review_price": "xem lại giá",
            "growth_opportunity": "cơ hội tăng trưởng",
            "monitor": "theo dõi",
            "consider_exit": "cân nhắc rút lui",
        },
        "balance": "## 10. Cân bằng hàng đi / hàng về (các thành phố lệch nhất)",
        "bal_cols": ["Thành phố", "Lô đi", "Lô đến", "Chênh lệch", "Mức lệch"],
        "moves": "## 11. Xe bắt đầu chuyến ở nơi khác điểm kết thúc chuyến trước",
        "move_cols": ["Năm", "Số lần chuyển", "Bắt đầu ở nơi khác", "Tỷ lệ"],
        "notebook": "## 12. Đối chiếu với notebook của tác giả bộ dữ liệu",
        "nb_cols": ["Phân tích", "Notebook", "Vấn đề", "Ở đây"],
        "nb_rows": [
            (
                "Ma trận tuyến",
                "Nhiên liệu cố định $3,80/gallon; doanh thu không gồm phụ phí; "
                "trung bình biên từng lô",
                "Giá giả định; doanh thu thiếu; trung bình của tỷ lệ",
                "Chi tiêu nhiên liệu thật, doanh thu đầy đủ, tổng ÷ tổng; giá trung bình {price}",
            ),
            (
                "Hàng đi/hàng về",
                "Chi phí điều xe = |tổng chênh lệch| × 400 dặm × $0,85",
                "Tổng chênh lệch của mọi thành phố luôn bằng 0, nên chi phí luôn là $0; số dặm và "
                "đơn giá là giả định",
                "Đo phần dư chiều đến theo từng thành phố: {surplus} lô",
            ),
            (
                "Tập trung khách hàng",
                "Thị phần top 10/20, ngưỡng rủi ro 10%",
                "Không có",
                "Giữ nguyên, thêm HHI {hhi}",
            ),
            (
                "Mùa vụ",
                "Đếm số lô theo tháng, so đỉnh và đáy",
                "Tháng dài 28–31 ngày nên tháng dài luôn trông bận hơn",
                "Tính theo ngày: không có mẫu hình lặp lại",
            ),
            (
                "Dặm chạy rỗng",
                "Giả định 15% dặm rỗng, $0,85/dặm",
                "Cả hai con số đều giả định",
                "Đếm từ chuỗi chuyến: {moved} số lần chuyển; không tính dặm (4 thành phố "
                "trên tuyến không có tọa độ)",
            ),
        ],
        "thresholds": "## 13. Ngưỡng của các quy tắc",
        "th_cols": ["Ngưỡng", "Giá trị", "Lý do", "Nguồn"],
    },
}


def _dollars(f: NumberFormatter, lang: str, x: float) -> str:
    return f"${f.int(x)}" if lang == "en" else f"{f.int(x)} USD"


def _table(header, rows, right=()):
    align = ["---:" if i in right else "---" for i in range(len(header))]
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(align) + "|"]
    out += [
        "| " + " | ".join("—" if c is None else str(c).replace("|", r"\|") for c in r) + " |"
        for r in rows
    ]
    return out


def render(b: dict, lang: str) -> str:
    t, f = L[lang], NumberFormatter(lang)
    usd = lambda x: f.value(x, "usd_m")  # noqa: E731
    pct = lambda x: None if x is None else f.pct(x / 100)  # noqa: E731
    start, end = b["range"]
    out = [
        t["title"],
        "",
        t["banner"],
        "",
        t["range"].format(start=start, end=end),
        "",
        t["insights"],
        "",
    ]
    out += _table(
        [t["level"], t["comment"]], [[i["level_label"], i["text"]] for i in b["insights"][lang]]
    )

    out += ["", t["pnl"], ""]
    out += _table(
        t["pnl_cols"],
        [
            [
                r["period"],
                f.int(r["trips"]),
                usd(r["revenue"]),
                usd(r["fuel_cost"]),
                usd(r["maintenance_cost"]),
                usd(r["claims"]),
                usd(r["contribution"]),
                pct(r["margin_pct"]),
                pct(r["contribution_vs_prev_pct"]),
                pct(r["contribution_yoy_pct"]),
            ]
            for r in b["pnl"]["year"].iter_rows(named=True)
        ],
        range(1, 10),
    )
    out += ["", t["pnl_q"], ""]
    out += _table(
        t["pnl_q_cols"],
        [
            [
                r["period"],
                usd(r["revenue"]),
                usd(r["contribution"]),
                pct(r["margin_pct"]),
                pct(r["contribution_vs_prev_pct"]),
                pct(r["contribution_yoy_pct"]),
                usd(r["contribution_ytd"]),
                None if r["contribution_ytd_prior"] is None else usd(r["contribution_ytd_prior"]),
            ]
            for r in b["pnl"]["quarter"].iter_rows(named=True)
        ],
        range(1, 8),
    )

    years = b["pnl"]["year"]["period"].to_list()
    a, z = years[0], years[-1]
    br = b["bridge"]
    names = t["bridge_rows"]
    rows = [[names["start"].format(a=a), usd(br["start"])]]
    rows += [
        [names[p], ("+" if br["parts"][p] >= 0 else "") + usd(br["parts"][p])] for p in BRIDGE_PARTS
    ]
    rows += [[names["end"].format(b=z), usd(br["end"])]]
    out += ["", t["bridge"].format(a=a, b=z), ""] + _table(["", ""], rows, {1})

    out += ["", t["units"], ""]
    out += _table(
        t["unit_cols"],
        [
            [
                r["period"],
                f.value(r["revenue_per_mile"], "usd"),
                f.value(r["cost_per_mile"], "usd"),
                f.value(r["contribution_per_mile"], "usd"),
                _dollars(f, lang, r["revenue_per_trip"]),
                _dollars(f, lang, r["contribution_per_trip"]),
                _dollars(f, lang, r["contribution_per_truck_week"]),
            ]
            for r in b["unit_economics"].iter_rows(named=True)
        ],
        range(1, 7),
    )

    out += ["", t["dims"], ""]
    for dim, title in t["dim_titles"].items():
        table = (
            b["dimensions"][dim]
            .filter(~pl.col("is_total"))
            .sort("contribution", descending=True)
            .head(8)
        )
        out += [f"**{title}**", ""]
        out += _table(
            t["dim_cols"],
            [
                [
                    r["group"],
                    usd(r["revenue"]),
                    usd(r["contribution"]),
                    pct(r["contribution_margin_pct"]),
                    pct(r["contribution_share_pct"]),
                ]
                for r in table.iter_rows(named=True)
            ],
            {1, 2, 3, 4},
        )
        out.append("")
    c = b["concentration"]
    out += [
        t["conc"].format(
            largest=pct(c["largest_pct"]),
            top10=pct(c["top10_pct"]),
            top20=pct(c["top20_pct"]),
            n80=c["customers_for_80pct"],
            n=c["customers"],
            hhi=f.int(c["hhi"]),
        )
    ]

    out += ["", t["fuel"], ""]
    out += _table(
        t["fuel_cols"],
        [
            [
                r["period"],
                f.int(r["gallons_bought"]),
                usd(r["spend"]),
                f.value(r["avg_price"], "usd"),
                f.int(r["gallons_burned"]),
                f.num(r["bought_to_burned"], 2),
            ]
            for r in b["fuel"]["year"].iter_rows(named=True)
        ],
        range(1, 6),
    )
    out += ["", t["fuel_corr"].format(corr=f.num(b["facts"]["margin_fuel_corr"], 2))]

    cap = b["capacity"]
    out += ["", t["cap"], ""]
    out += _table(
        t["cap_cols"],
        [
            [r["year"], f.num(r["mean"], 1), f.num(r["p95"], 0), r["max"]]
            for r in cap["by_year"].iter_rows(named=True)
        ],
        {1, 2, 3},
    )
    out += [
        "",
        t["cap_note"].format(
            p95=f.int(cap["p95"]),
            p99=f.int(cap["p99"]),
            mx=cap["max"],
            in_use=cap["trucks_in_use"],
            owned=cap["trucks_owned"],
            lag1=f.num(cap["lag1_autocorrelation"], 2),
            qp=f.num(cap["quarter_persistence"], 2),
        ),
    ]

    m = b["lane_matrix"]
    out += ["", t["matrix"], ""]
    grid = []
    for vt in (3, 2, 1):
        row = [t["tiers"][vt]]
        for mt in (1, 2, 3):
            cell = m.filter((pl.col("volume_tier") == vt) & (pl.col("margin_tier") == mt))
            action = cell["action"][0] if cell.height else None
            row.append(f"{cell.height} ({t['actions'][action]})" if action else "0")
        grid.append(row)
    out += _table(t["matrix_head"], grid)

    bal = b["balance"]["cities"].head(8)
    out += ["", t["balance"], ""]
    out += _table(
        t["bal_cols"],
        [
            [
                r["city"],
                f.int(r["loads_out"]),
                f.int(r["loads_in"]),
                f.int(r["net"]),
                pct(r["imbalance_pct"]),
            ]
            for r in bal.iter_rows(named=True)
        ],
        {1, 2, 3, 4},
    )

    out += ["", t["moves"], ""]
    out += _table(
        t["move_cols"],
        [
            [r["yr"], f.int(r["transitions"]), f.int(r["moved"]), pct(r["moved_pct"])]
            for r in b["repositioning"]["by_year"].iter_rows(named=True)
        ],
        {1, 2, 3},
    )

    avg_price = b["fuel"]["year"]["spend"].sum() / b["fuel"]["year"]["gallons_bought"].sum()
    values = {
        "price": f.value(avg_price, "usd"),
        "surplus": f.int(b["facts"]["surplus"]),
        "hhi": f.int(c["hhi"]),
        "moved": pct(b["facts"]["moved_pct"]),
    }
    out += ["", t["notebook"], ""]
    out += _table(
        t["nb_cols"], [[a_, n_, i_, h_.format(**values)] for a_, n_, i_, h_ in t["nb_rows"]]
    )

    out += ["", t["thresholds"], ""]
    out += _table(
        t["th_cols"],
        [
            [
                name,
                f.num(v, 1),
                REASONS_VI[name] if lang == "vi" else reason,
                f"[{src}]({SOURCES[src]})"
                if src in SOURCES
                else ("dự án" if lang == "vi" else src),
            ]
            for name, (v, reason, src) in THRESHOLDS.items()
        ],
        {1},
    )
    return "\n".join(out) + "\n"


def write_analysis_docs(db_path: Path, docs_dir: Path) -> list[Path]:
    with duckdb.connect(str(db_path), read_only=True) as con:
        b = analysis_bundle(con)
    paths = []
    for lang in LANGUAGES:
        path = docs_dir / L[lang]["file"]
        path.write_text(render(b, lang), encoding="utf-8", newline="\n")
        paths.append(path)
    return paths
