"""Render docs/03-kpi-definitions(.vi).md from the KPI catalog plus the fleet value of each KPI.

Generated by `logops build`, so the definitions can't drift from the code in kpis.py.
"""

import datetime as dt
from pathlib import Path

import duckdb

from logops.data_platform.dq_report import NumberFormatter
from logops.metrics.kpis import CATALOG, FLEET, kpi

LANGUAGES = ("en", "vi")

LABELS = {
    "en": {
        "file": "03-kpi-definitions.md",
        "title": "# 03 · KPI Definitions",
        "banner": "> CRISP-DM phase 3 (Data Preparation). Generated by `uv run logops build` from "
        "the catalog in `src/logops/metrics/kpis.py`; do not edit by hand. · Vietnamese: "
        "[03-kpi-definitions.vi.md](03-kpi-definitions.vi.md) · Spec: "
        "[SPEC-metrics.md](../SPEC-metrics.md)",
        "intro": "Fleet values cover {start} to {end}. Every ratio is a sum divided by a sum. "
        "Costs that can't be tied to a trip are in an *Unattributed* line, so groups always "
        "add up to the fleet total. Use `uv run logops kpi --by route` to see any breakdown.",
        "kpi": "KPI",
        "unit": "Unit",
        "formula": "Formula",
        "fleet": "Fleet value",
        "areas": {
            "Cost": "Cost",
            "Fuel": "Fuel",
            "Reliability": "Delivery reliability",
            "Assets": "Assets",
            "Safety": "Safety",
        },
        "allocation": "## How costs are assigned to trips",
        "allocation_rows": [
            "**Fuel:** the month's fuel spend, split across that month's trips by gallons burned. "
            "Fuel purchases aren't reliably linked to trips (29% more gallons bought than burned).",
            "**Maintenance:** a truck's cost in a month, split across its trips that month by "
            "miles. Maintenance of trucks that ran no trip that month is *Unattributed*.",
            "**Incidents:** directly by trip.",
            "**Driver pay:** not in the data, so not included. Contribution is before driver pay.",
        ],
        "excluded": "## Not measured, and why",
        "excluded_rows": [
            "**Idle time:** `idle_time_hours` is random noise (correlation ≈ 0 with trip "
            "duration, distance and fuel).",
            "**Fuel price by location:** prices differ by only $0.02/gallon across cities.",
            "**By facility:** `facility_id` on delivery events is essentially random; "
            "`location_city` is used instead.",
        ],
    },
    "vi": {
        "file": "03-kpi-definitions.vi.md",
        "title": "# 03 · Định nghĩa KPI",
        "banner": "> CRISP-DM pha 3 (Chuẩn bị dữ liệu). Sinh tự động bằng `uv run logops build` từ "
        "danh mục trong `src/logops/metrics/kpis.py`; không sửa tay. · Bản tiếng Anh: "
        "[03-kpi-definitions.md](03-kpi-definitions.md) · Spec: "
        "[SPEC-metrics.vi.md](../SPEC-metrics.vi.md)",
        "intro": "Giá trị đội xe tính từ {start} đến {end}. Mọi tỷ lệ là tổng chia tổng. Chi phí "
        "không gán được vào chuyến nằm ở dòng *Không gán được*, nên các nhóm luôn cộng lại "
        "bằng tổng đội xe. Dùng `uv run logops kpi --by route` để xem theo từng nhóm.",
        "kpi": "KPI",
        "unit": "Đơn vị",
        "formula": "Công thức",
        "fleet": "Giá trị đội xe",
        "areas": {
            "Cost": "Chi phí",
            "Fuel": "Nhiên liệu",
            "Reliability": "Độ tin cậy giao hàng",
            "Assets": "Tài sản",
            "Safety": "An toàn",
        },
        "allocation": "## Cách gán chi phí vào chuyến",
        "allocation_rows": [
            "**Nhiên liệu:** tiền mua nhiên liệu trong tháng, chia cho các chuyến trong tháng theo "
            "gallon tiêu thụ. Phiếu nhiên liệu không gán đúng chuyến (gallon mua nhiều hơn gallon "
            "tiêu thụ 29%).",
            "**Bảo dưỡng:** chi phí của xe trong tháng, chia cho các chuyến của xe trong tháng "
            "theo dặm. Bảo dưỡng của xe không chạy chuyến nào trong tháng là *Không gán được*.",
            "**Sự cố:** gán thẳng theo chuyến.",
            "**Lương tài xế:** dữ liệu không có nên không tính. Biên đóng góp là trước lương "
            "tài xế.",
        ],
        "excluded": "## Không đo, và vì sao",
        "excluded_rows": [
            "**Thời gian chạy không tải:** `idle_time_hours` là nhiễu ngẫu nhiên (tương quan ≈ 0 "
            "với thời gian chuyến, quãng đường và nhiên liệu).",
            "**Giá nhiên liệu theo địa điểm:** giá giữa các thành phố chỉ chênh 0,02 USD/gallon.",
            "**Theo kho:** `facility_id` trên sự kiện giao nhận gần như ngẫu nhiên; dùng "
            "`location_city` thay thế.",
        ],
    },
}


def doc_path(docs_dir: Path, lang: str) -> Path:
    return docs_dir / LABELS[lang]["file"]


def fleet_values(con: duckdb.DuckDBPyConnection, start: dt.date, end: dt.date) -> dict:
    table = kpi(con, start, end)
    (row,) = [r for r in table.iter_rows(named=True) if r["group"] == FLEET]
    return row


def render(values: dict, start: dt.date, end: dt.date, lang: str) -> str:
    t = LABELS[lang]
    f = NumberFormatter(lang)
    out = [t["title"], "", t["banner"], "", t["intro"].format(start=start, end=end), ""]
    for area, heading in t["areas"].items():
        out += [
            f"## {heading}",
            "",
            f"| {t['kpi']} | {t['unit']} | {t['formula']} | {t['fleet']} |",
        ]
        out.append("|---|---|---|---:|")
        for k in (k for k in CATALOG if k.area == area):
            value = values[k.name]
            shown = "—" if value is None else f.num(value, 3 if abs(value) < 10 else 1)
            formula = k.formula[lang].replace("|", r"\|")  # keep table cells intact
            out.append(f"| `{k.name}` | {k.unit} | {formula} | {shown} |")
        out.append("")
    out += [t["allocation"], ""] + [f"- {r}" for r in t["allocation_rows"]] + [""]
    out += [t["excluded"], ""] + [f"- {r}" for r in t["excluded_rows"]]
    return "\n".join(out) + "\n"


def write_kpi_docs(db_path: Path, docs_dir: Path) -> list[Path]:
    with duckdb.connect(str(db_path), read_only=True) as con:
        start, end = con.execute(
            "SELECT min(dispatch_date), (SELECT max(purchase_date)::DATE FROM fuel_purchases) "
            "FROM trips"
        ).fetchone()
        values = fleet_values(con, start, end)
    paths = []
    for lang in LANGUAGES:
        path = doc_path(docs_dir, lang)
        path.write_text(render(values, start, end, lang), encoding="utf-8", newline="\n")
        paths.append(path)
    return paths
